"""
Step 7: Automated tutoring-video renderer.

The original tutoring video remains the base layer.

For every scene:
    - read scene start/end timestamps
    - find the assigned image
    - resize/crop the image
    - place it inside the whiteboard region
    - keep the tutor visible
    - preserve the original audio

Input:
    data/raw_videos/{video_id}.mp4
    data/image_queries/{video_id}_assignments.json

Output:
    data/rendered_videos/{video_id}_rendered.mp4

Usage:
    python scripts/07_render_video.py --video-id CORT_sample_video_2
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.append(
    str(Path(__file__).parent.parent)
)

import config


def run_command(command: list[str]):
    """
    Run an external command and raise an error if it fails.
    """

    print()
    print("Running:")
    print(" ".join(str(x) for x in command))
    print()

    subprocess.run(
        command,
        check=True,
    )


def load_assignments(video_id: str) -> list:
    """
    Load image assignments generated by Step 5.
    """

    path = (
        config.IMAGE_QUERIES_DIR
        / f"{video_id}_assignments.json"
    )

    if not path.exists():
        raise FileNotFoundError(
            f"Assignment file not found:\n{path}"
        )

    return json.loads(
        path.read_text()
    )


def validate_source_video(video_id: str) -> Path:
    """
    Locate the original video.
    """

    video_path = (
        config.RAW_VIDEOS_DIR
        / f"{video_id}.mp4"
    )

    if not video_path.exists():
        raise FileNotFoundError(
            f"Source video not found:\n{video_path}"
        )

    return video_path


def build_scene_filter(
    assignment: dict,
    image_input_index: int,
) -> str:
    """
    Build FFmpeg filter for one image.

    The image is scaled/cropped to the whiteboard dimensions
    and overlaid only during the scene's time interval.
    """

    start = float(
        assignment["start"]
    )

    end = float(
        assignment["end"]
    )

    x = config.WHITEBOARD_X
    y = config.WHITEBOARD_Y

    width = config.WHITEBOARD_WIDTH
    height = config.WHITEBOARD_HEIGHT

    image_label = f"img{image_input_index}"

    # ---------------------------------------------------------
    # Prepare image
    # ---------------------------------------------------------

    image_filter = (
        f"[{image_input_index}:v]"
        f"scale={width}:{height}:"
        f"force_original_aspect_ratio=increase,"
        f"crop={width}:{height},"
        f"setsar=1"
        f"[{image_label}]"
    )

    # ---------------------------------------------------------
    # Overlay image during scene
    # ---------------------------------------------------------

    return (
        image_filter
        + ";"
        + f"[base][{image_label}]"
        f"overlay={x}:{y}:"
        f"enable='between(t,{start},{end})'"
        f"[scene{image_input_index}]"
    )


def render_video(
    video_id: str,
    max_duration: float | None = None,
):
    """
    Render the complete video.
    """

    source_video = validate_source_video(
        video_id
    )

    assignments = load_assignments(
        video_id
    )

    config.RENDERED_VIDEOS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_path = (
        config.RENDERED_VIDEOS_DIR
        / f"{video_id}_rendered.mp4"
    )

    # ---------------------------------------------------------
    # Collect assignments that have valid images
    # ---------------------------------------------------------

    valid_assignments = []

    for assignment in assignments:

        image_path = assignment.get(
            "local_path"
        )

        image_id = assignment.get(
            "image_id"
        )

        if not image_id:
            print(
                f"[skip] "
                f"{assignment.get('scene_id')} "
                f"— no image assigned"
            )

            continue

        if not image_path:

            print(
                f"[skip] "
                f"{assignment.get('scene_id')} "
                f"— image path missing"
            )

            continue

        image_file = Path(
            image_path
        )

        if not image_file.exists():

            print(
                f"[skip] "
                f"{assignment.get('scene_id')} "
                f"— image file missing:"
            )

            print(
                f"       {image_file}"
            )

            continue

        # Don't render images that failed validation.
        validation_status = assignment.get(
            "validation_status"
        )

        if validation_status == "FAIL":

            print(
                f"[skip] "
                f"{assignment.get('scene_id')} "
                f"— image failed validation"
            )

            continue

        valid_assignments.append(
            assignment
        )

    # ---------------------------------------------------------
    # Check whether we have images
    # ---------------------------------------------------------

    if not valid_assignments:

        raise RuntimeError(
            "No valid images are available for rendering."
        )

    print()
    print("=" * 60)
    print("STEP 7 — VIDEO RENDERING")
    print("=" * 60)

    print(
        f"Video ID:        {video_id}"
    )

    print(
        f"Source:          {source_video}"
    )

    print(
        f"Scenes total:    {len(assignments)}"
    )

    print(
        f"Images usable:   {len(valid_assignments)}"
    )

    print(
        f"Output:          {output_path}"
    )

    print("=" * 60)

    # ---------------------------------------------------------
    # Build FFmpeg command
    # ---------------------------------------------------------

    command = [
        "ffmpeg",
        "-y",

        # Original video
        "-i",
        str(source_video),
    ]

    # ---------------------------------------------------------
    # Add image inputs
    # ---------------------------------------------------------

    for assignment in valid_assignments:

        command.extend(
            [
                "-loop",
                "1",
                "-i",
                str(
                    assignment["local_path"]
                ),
            ]
        )

    # ---------------------------------------------------------
    # Build filter graph
    # ---------------------------------------------------------

    filter_parts = []

    # Base video
    filter_parts.append(
        "[0:v]"
        f"scale={config.RENDER_WIDTH}:"
        f"{config.RENDER_HEIGHT}:"
        "force_original_aspect_ratio=decrease,"
        f"pad={config.RENDER_WIDTH}:"
        f"{config.RENDER_HEIGHT}:"
        "(ow-iw)/2:"
        "(oh-ih)/2,"
        "setsar=1"
        "[base]"
    )

    previous_label = "base"

    # ---------------------------------------------------------
    # Overlay each image
    # ---------------------------------------------------------

    for index, assignment in enumerate(
        valid_assignments,
        start=1,
    ):

        input_index = index

        start = float(
            assignment["start"]
        )

        end = float(
            assignment["end"]
        )

        x = config.WHITEBOARD_X
        y = config.WHITEBOARD_Y

        width = config.WHITEBOARD_WIDTH
        height = config.WHITEBOARD_HEIGHT

        image_label = (
            f"img{index}"
        )

        output_label = (
            f"v{index}"
        )

        # Image preparation
        filter_parts.append(
            f"[{input_index}:v]"
            f"scale={width}:{height}:"
            "force_original_aspect_ratio=increase,"
            f"crop={width}:{height},"
            "setsar=1"
            f"[{image_label}]"
        )

        # Overlay
        filter_parts.append(
            f"[{previous_label}]"
            f"[{image_label}]"
            f"overlay={x}:{y}:"
            f"enable='between(t,{start},{end})'"
            f"[{output_label}]"
        )

        previous_label = output_label

    filter_complex = ";".join(
        filter_parts
    )

    command.extend(
        [
            "-filter_complex",
            filter_complex,

            # Final video stream
            "-map",
            f"[{previous_label}]",

            # Original audio
            "-map",
            "0:a?",

            # Encoding
            "-c:v",
            "libx264",

            "-preset",
            "medium",

            "-crf",
            "20",

            "-pix_fmt",
            "yuv420p",

            # Audio
            "-c:a",
            "aac",

            "-b:a",
            "192k",

            # Frame rate
            "-r",
            str(config.RENDER_FPS),

            # Optional test duration
        ]
    )

    if max_duration is not None:

        command.extend(
            [
                "-t",
                str(max_duration),
            ]
        )

    command.append(
        str(output_path)
    )

    # ---------------------------------------------------------
    # Execute
    # ---------------------------------------------------------

    run_command(
        command
    )

    # ---------------------------------------------------------
    # Final report
    # ---------------------------------------------------------

    print()
    print("=" * 60)
    print("VIDEO RENDER COMPLETE")
    print("=" * 60)

    print(
        f"Video ID:       {video_id}"
    )

    print(
        f"Resolution:     "
        f"{config.RENDER_WIDTH}x"
        f"{config.RENDER_HEIGHT}"
    )

    print(
        f"FPS:            "
        f"{config.RENDER_FPS}"
    )

    print(
        f"Images used:    "
        f"{len(valid_assignments)}"
    )

    print(
        f"Output:"
    )

    print(
        f"  {output_path}"
    )

    print("=" * 60)


def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--video-id",
        required=True,
    )

    parser.add_argument(
        "--test-duration",
        type=float,
        default=None,
        help=(
            "Render only the first N seconds "
            "for testing."
        ),
    )

    args = parser.parse_args()

    render_video(
        args.video_id,
        max_duration=args.test_duration,
    )


if __name__ == "__main__":
    main()